### ISSUE TITLE
About the paper released.

### ISSUE THREAD

**Issue by gaiyi7788** [hnuzhy/SSDA-YOLO#1]
Excuse me, when will the paper released?

**Comment by hnuzhy** [comment]
> Excuse me, when will the paper released?

Thank you for your attention. I have uploaded a preprint paper to the Arxiv. It will be available no more than two days. You can check this repository later.

**Comment by gaiyi7788** [comment]
Thank you very much for your timely reply!

**Comment by hnuzhy** [comment]
> 

I have added the Arxiv link of my manuscript paper. You can check it now~

**Comment by hnuzhy** [comment]
> Thank you very much for your timely reply!

I have added the Arxiv link of my manuscript paper. You can check it now~
