### ISSUE TITLE
请教一下，关于对yaml文件中五个数据集设置的疑惑

### ISSUE THREAD

**Issue by IssacaLaw** [hnuzhy/SSDA-YOLO#10]
假如我想自定义数据集训练一个检测雾中船舶的模型，现有数据集a和b，则train_source_real中代表的是不是带有标签的真实图像的船舶数据集a；train_source_fake中代表的是不是带有标签的经过雾化处理的真实的船舶数据集a；train_target_real中代表的是不是没有标签的经过雾化处理的真实的船舶数据集b；train_target_fake中代表的的是不是没有标签的真实的船舶数据集b；test_target_real中则用一些雾化的数据集用于验证呢？ 望解答一下！！

**Comment by hnuzhy** [comment]
train_source_real和train_source_fake的理解是对的。后两个反了，train_target_real指的是目标域真实的船舶数据集；train_target_fake指的是目标域虚假的船舶数据集，也就是经过CUT图像风格迁移，全局特征偏向源域。另外，目标域的标签只需要给测试集提供，用来验证domain adaptation是否提升了检测效果，更大的目标域测试集则不需要GT标签。

**Comment by IssacaLaw** [comment]
> train_source_real和train_source_fake的理解是对的。后两个反了，train_target_real指的是目标域真实的船舶数据集；train_target_fake指的是目标域虚假的船舶数据集，也就是经过CUT图像风格迁移，全局特征偏向源域。另外，目标域的标签只需要给测试集提供，用来验证domain adaptation是否提升了检测效果，更大的目标域测试集则不需要GT标签。

感谢回复和帮助！

**Comment by IssacaLaw** [comment]
你好周博士，继这个问题，train_target_real和train_target_fake按道理是不需要标签的，但是当我在images文件夹中的train文件夹中只放图片文件时，而和images同级的目录下无labels文件夹时，进行训练提示目标域即train_target_real和train_target_fake没有标签无法进行训练。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hnuzhy/SSDA-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 凌晨0:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10)





 
train_source_real和train_source_fake的理解是对的。后两个反了，train_target_real指的是目标域真实的船舶数据集；train_target_fake指的是目标域虚假的船舶数据集，也就是经过CUT图像风格迁移，全局特征偏向源域。另外，目标域的标签只需要给测试集提供，用来验证domain adaptation是否提升了检测效果，更大的目标域测试集则不需要GT标签。

**Comment by hnuzhy** [comment]
目标域的训练集标签是为了测试监督学习的upper-bound，也就是得到Oracle那一行的数值，实际应用中，没有目标域训练集的标签可以不计算Oracle。脚本默认是加载标签的，如果报错，需要你在train.py文件里找到加载该子训练集的代码，修改之发自我的手机-------- 原始邮件 --------发件人： 罗浩轩 ***@***.***>日期： 2023年4月10日周一 晚上8:08收件人： hnuzhy/SSDA-YOLO ***@***.***>抄送： Huayi Zhou ***@***.***>, Comment ***@***.***>主    题： Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10)
你好周博士，继这个问题，train_target_real和train_target_fake按道理是不需要标签的，但是当我在images文件夹中的train文件夹中只放图片文件时，而和images同级的目录下无labels文件夹时，进行训练提示目标域即train_target_real和train_target_fake没有标签无法进行训练。













------------------&nbsp;原始邮件&nbsp;------------------

发件人:                                                                                                                        "hnuzhy/SSDA-YOLO"                                                                                    ***@***.***&gt;;

发送时间:&nbsp;2023年3月29日(星期三) 凌晨0:22

***@***.***&gt;;

***@***.******@***.***&gt;;

主题:&nbsp;Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10)











 

train_source_real和train_source_fake的理解是对的。后两个反了，train_target_real指的是目标域真实的船舶数据集；train_target_fake指的是目标域虚假的船舶数据集，也就是经过CUT图像风格迁移，全局特征偏向源域。另外，目标域的标签只需要给测试集提供，用来验证domain adaptation是否提升了检测效果，更大的目标域测试集则不需要GT标签。

**Comment by IssacaLaw** [comment]
首先感谢周博士的再次回复！
在我研究ssda_yolov5_train.py文件时，不确定具体怎么修改，目前只猜测在以下两部分进行修改可以令其不加载子训练集，


1.

2.

学生知识技术未过关，寻chatgpt帮助也未果，还请周博士再指导一下！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hnuzhy/SSDA-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 晚上10:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10)





 目标域的训练集标签是为了测试监督学习的upper-bound，也就是得到Oracle那一行的数值，实际应用中，没有目标域训练集的标签可以不计算Oracle。脚本默认是加载标签的，如果报错，需要你在train.py文件里找到加载该子训练集的代码，修改之发自我的手机-------- 原始邮件 --------发件人： 罗浩轩 ***@***.***&gt;日期： 2023年4月10日周一 晚上8:08收件人： hnuzhy/SSDA-YOLO ***@***.***&gt;抄送： Huayi Zhou ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10) 
 你好周博士，继这个问题，train_target_real和train_target_fake按道理是不需要标签的，但是当我在images文件夹中的train文件夹中只放图片文件时，而和images同级的目录下无labels文件夹时，进行训练提示目标域即train_target_real和train_target_fake没有标签无法进行训练。 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 
 发件人:                                                                                                                        "hnuzhy/SSDA-YOLO"                                                                                    ***@***.***&amp;gt;; 
 
 发送时间:&amp;nbsp;2023年3月29日(星期三) 凌晨0:22 
 
 ***@***.***&amp;gt;; 
 
 ***@***.******@***.***&amp;gt;; 
 
 主题:&amp;nbsp;Re: [hnuzhy/SSDA-YOLO] 请教一下，关于对yaml文件中五个数据集设置的疑惑 (Issue #10) 
 
 
 
 
 
 
 
 
 
 
 
   
 
 train_source_real和train_source_fake的理解是对的。后两个反了，train_target_real指的是目标域真实的船舶数据集；train_target_fake指的是目标域虚假的船舶数据集，也就是经过CUT图像风格迁移，全局特征偏向源域。另外，目标域的标签只需要给测试集提供，用来验证domain adaptation是否提升了检测效果，更大的目标域测试集则不需要GT标签。

**Comment by DuyunliangToon** [comment]
您好，还是关于这个问题，看了上面的问题和回复，我对ssda_yolov5_train.py文件进行了研究，个人能力有限，希望周博士指导一下怎么修改代码才能不加载目标域的训练集标签，期待您的回复。
