### ISSUE TITLE
The width and height of the real and fake images are inconsistent

### ISSUE THREAD

**Issue by EudicL** [hnuzhy/SSDA-YOLO#11]
img, _, (h, w) = load_image(self, index)
 img_fake, _, (h, w) = load_image(self, index, type="fake")

**Comment by hnuzhy** [comment]
This is a drawback of CUT model. It will change the shape/size of the original image slightly during style transfer. Usually, one or two pixel offsets in width or height. You can simply resize the corresponding face images into their original shapes. This will not affect much.

**Comment by EudicL** [comment]
Thank you for your kindness.
