### ISSUE TITLE
Can you help me with this problem?

### ISSUE THREAD

**Issue by EudicL** [hnuzhy/SSDA-YOLO#12]
when I trained the ssda_yolov5, the error was as follows:
 File "ssda_yolov5_train.py", line 548, in train
    loss_items[3] += loss_cons.detach()[0]  # (lbox, lobj, lcls, total_loss)
IndexError: index 3 is out of bounds for dimension 0 with size 3

And I print the shape of the 'loss_item', which is a tensor size of 3.

**Comment by hnuzhy** [comment]
The length of 'loss_item' should be 4. Did you change the loss function? You can refer it in https://github.com/hnuzhy/SSDA-YOLO/blob/master/utils/loss.py#L166

**Comment by EudicL** [comment]
Yes, I changed the loss function and it has been solved now. I appreciate your courteous reply.
