### ISSUE TITLE
How to keep the object label position invariance in a specific dataset such as the Yawn dataset?

### ISSUE THREAD

**Issue by kevinkevin886** [hnuzhy/SSDA-YOLO#13]
Hi Author, I have a curious question to ask how to solve the problem of object label position offset ?

In the paper conclusion, "we apply a consistency loss function to correct the prediction shifts of images from different domains but with same labels." Similarly, In Fig.1, the yellow and gray branches need to keep the two images(source domain and target-like souce domain) with the same object label. It is obvious that this behavior can be maintained in VOC and Cityscapes task. 
However, for example, whether the angle transformation of the camera will cause the object label position to shift or genearate new object without object label in the fake image generated by CUT. In the same situation, in yawnling data set, there will also be differences in camer angle and different positions of tables, chairs and characters.
Thanks a lot for taking the time to review this question.

**Comment by hnuzhy** [comment]
CUT is a GAN-based generation method which will not lead to too much affine deformation or introduce new irrelevant objects. It just gives a scene-level image style transformation. These concerns might only be real for recent Diffuison-based or Flow-based generation models.

**Comment by HuangJyunKai** [comment]
So in yawn data set, only the material of the table or the color of the children’s clothes will change, and the rest will remain unchanged.
Got it. Thank you for your prompt reply!

**Comment by kevinkevin886** [comment]
So in yawn data set, only the material of the table or the color of the children’s clothes will change, and the rest will remain unchanged.
Got it. Thank you for your prompt reply!
