### ISSUE TITLE
Generated CUT Images for Cityscapes -> Foggy

### ISSUE THREAD

**Issue by ShpihanVlad** [hnuzhy/SSDA-YOLO#15]
Hi, nice work
Will you upload your images generated by CUT model for Cityscapers to Foggy Cityscapes style and vice versa?
Thanks

**Comment by hnuzhy** [comment]
I have uploaded these files. You can download them by following link https://github.com/hnuzhy/SSDA-YOLO/tree/master#cityscapes--cityscapes-foggy

**Comment by ShpihanVlad** [comment]
Cool, thanks!
